# Generated by Django 4.1.4 on 2023-03-15 13:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myblog", name="blog_desc", field=tinymce.models.HTMLField(),
        ),
    ]
